name: Deploy NotesKeeperBot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Подключиться по SSH и выполнить деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/botuser/noteskeeperbot
      
            git fetch origin
            git reset --hard origin/main
            
            docker compose -f /home/botuser/noteskeeperbot/compose.yaml --env-file /home/botuser/noteskeeperbot/.env down || true
            docker compose -f /home/botuser/noteskeeperbot/compose.yaml --env-file /home/botuser/noteskeeperbot/.env build --no-cache
            docker compose -f /home/botuser/noteskeeperbot/compose.yaml --env-file /home/botuser/noteskeeperbot/.env up -d
            docker compose -f /home/botuser/noteskeeperbot/compose.yaml --env-file /home/botuser/noteskeeperbot/.env ps